#!/usr/bin/python3
"""
Model_state module contains the city class
"""


from sqlalchemy import Column, Integer, String
from model_state import Base, State
from sqlalchemy.schema import ForeignKey
class City(Base):
    """
    State class store id autogenerated
    and store name column size of 128 characters
    """
    __tablename__ = 'cities'
    id = Column(Integer, primary_key=True, nullable=False)
    name = Column(String(128))
    state_id = Column(Integer, ForeignKey("states.id"), nullable=False)
